---
# tasks file for TmuxCsshInstall
- name: Get primary group for {{UserName}}
  shell: /usr/bin/id -gn "{{UserName}}"
  register: PrimaryGroup

- name: tmux-cssh for {{UserName}}
  get_url:
    url: "{{TmuxCsshUrl}}"
    dest: "~{{UserName}}/bin/tmux-cssh"
    owner: "{{UserName}}"
    group: "{{PrimaryGroup.stdout}}"
    mode: 0755
    validate_certs: no
    force: yes
