---
- name: "create bin dir if it doesn't exist"
  file:
    path: "/home/{{item.UserName}}/bin"
    owner:  "{{item.UserName}}"
    group:  "{{item.PrimaryGroup| default('users')}}"
    state:  directory
  with_items: "{{Users}}"
  loop_control:
    label: "{{item.UserName}}"
- name: tmux-cssh for {{item.UserName}}
  get_url:
    url: "{{TmuxCsshUrl}}"
    dest: "~{{item.UserName}}/bin/tmux-cssh"
    owner: "{{item.UserName}}"
    group: "{{item.PrimaryGroup| default('users')}}"
    mode: 0755
    validate_certs: no
    force: yes
  with_items: "{{Users}}"
  loop_control:
    label: "{{item.UserName}}"